apiVersion: v1
kind: Service
metadata:
  name: hpa-demo-nodeport
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # Specify the NodePort value you prefer
  selector:
    run: hpa-demo-deployment
