---
apiVersion: v1
kind: Service
metadata:
 name: hpa-demo-deployment
 labels:
   run: hpa-demo-deployment
spec:
 ports:
 - port: 80
   nodePort: 30001
   protocol: TCP
 selector:
   run: hpa-demo-deployment